import 'package:get/get.dart';

enum TextEnum {
  appName(en: "App Name", bn: "অ্যাপ নাম"),
  verify(en: "Verify", bn: "যাচাই করুন"),
  send(en: "Send", bn: "পাঠান"),
  submit(en: "Submit", bn: "জমা দিন"),
  ok(en: "OK", bn: "ঠিক আছে"),
  cancel(en: "Cancel", bn: "বাতিল করুন"),
  resend(en: "Resend", bn: "পুনরায় পাঠান"),
  about(en: "About", bn: "সম্পর্কে"),
  contactUs(en: "Contact Us", bn: "যোগাযোগ করুন"),
  loginDescription(
      en: "Enter your credentials to login", bn: "লগইন করতে আপনার তথ্য দিন"),
  loginUpperText(en: "Login to continue", bn: "চালিয়ে যাওয়ার জন্য লগইন করুন"),
  next(en: "Next", bn: "পরবর্তী"),
  otpResend(
      en: "OTP will be sent again in @time", bn: '@time এবার OTP পাঠাবেন'),

  otpVerification(en: "OTP Verification", bn: "OTP যাচাইকরণ"),
  otpSentTo(
      en: "Please check, a verification code has been sent to @phone",
      bn: "@phone নম্বরে একটি যাচাইকরণ কোড পাঠানো হয়েছে"),
  changeNumber(en: "Change Number", bn: "নম্বর পরিবর্তন করুন"),

  phoneNumber(en: "Phone Number", bn: "ফোন নম্বর"),
  pin(en: "PIN", bn: "পিন"),
  createAccount(en: "Create new account", bn: "নতুন অ্যাকাউন্ট তৈরি করুন"),
  // BOS-010 F2 building application
  buildingApplications(en: "My building applications", bn: "আমার ভবন আবেদন"),
  registerBuilding(en: "Register a building", bn: "ভবন নিবন্ধন করুন"),
  newApplication(en: "New application", bn: "নতুন আবেদন"),
  editApplication(en: "Edit application", bn: "আবেদন সম্পাদনা"),
  applicationNumber(en: "Application no. @number", bn: "আবেদন নং @number"),
  noApplications(en: "You have no building applications yet.", bn: "আপনার এখনও কোনো ভবন আবেদন নেই।"),
  saveDraft(en: "Save draft", bn: "খসড়া সংরক্ষণ করুন"),
  submitApplication(en: "Submit application", bn: "আবেদন জমা দিন"),
  confirmSubmit(en: "Submit this application for review? You cannot change it while it is being reviewed.", bn: "পর্যালোচনার জন্য আবেদনটি জমা দেবেন? পর্যালোচনা চলাকালে এটি পরিবর্তন করা যাবে না।"),
  retry(en: "Retry", bn: "আবার চেষ্টা করুন"),
  edit(en: "Edit", bn: "সম্পাদনা"),
  documents(en: "Verification documents", bn: "যাচাইকরণ নথি"),
  noDocuments(en: "No documents yet. Add the deed, a holding tax receipt or other proof.", bn: "এখনও কোনো নথি নেই। দলিল, হোল্ডিং ট্যাক্সের রসিদ বা অন্য প্রমাণ যোগ করুন।"),
  addDocument(en: "Add document", bn: "নথি যোগ করুন"),
  takePhoto(en: "Take photo", bn: "ছবি তুলুন"),
  chooseFromGallery(en: "Choose from gallery", bn: "গ্যালারি থেকে বাছুন"),
  chooseFile(en: "Choose PDF file", bn: "PDF ফাইল বাছুন"),
  removeDocument(en: "Remove", bn: "সরান"),
  confirmRemoveDocument(en: "Remove this document?", bn: "এই নথিটি সরাবেন?"),
  reviewerMessage(en: "Message from the reviewer", bn: "পর্যালোচকের বার্তা"),
  rejectionReason(en: "Reason for rejection", bn: "প্রত্যাখ্যানের কারণ"),
  missingFieldsHint(en: "Complete the required fields to submit.", bn: "জমা দিতে প্রয়োজনীয় তথ্য পূরণ করুন।"),
  draftSaved(en: "Draft saved", bn: "খসড়া সংরক্ষিত হয়েছে"),
  applicationSubmitted(en: "Application submitted", bn: "আবেদন জমা হয়েছে"),
  documentAdded(en: "Document added", bn: "নথি যোগ হয়েছে"),
  sectionBuilding(en: "Building", bn: "ভবন"),
  sectionLocation(en: "Location", bn: "অবস্থান"),
  sectionContact(en: "Contact", bn: "যোগাযোগ"),
  fieldBuildingName(en: "Building name", bn: "ভবনের নাম"),
  fieldBuildingType(en: "Building type", bn: "ভবনের ধরন"),
  fieldAddress(en: "Address (house, road)", bn: "ঠিকানা (বাড়ি, রাস্তা)"),
  fieldArea(en: "Area", bn: "এলাকা"),
  fieldDistrict(en: "District", bn: "জেলা"),
  fieldPostalCode(en: "Postal code (optional)", bn: "পোস্ট কোড (ঐচ্ছিক)"),
  fieldTotalFloors(en: "Total floors (optional)", bn: "মোট তলা (ঐচ্ছিক)"),
  fieldEstimatedUnits(en: "Estimated units (flats, shops)", bn: "আনুমানিক ইউনিট (ফ্ল্যাট, দোকান)"),
  fieldRelationship(en: "Your relationship to the building", bn: "ভবনের সাথে আপনার সম্পর্ক"),
  fieldRelationshipNote(en: "Describe your relationship", bn: "আপনার সম্পর্ক বর্ণনা করুন"),
  fieldContactName(en: "Contact name", bn: "যোগাযোগকারীর নাম"),
  fieldContactPhone(en: "Contact phone", bn: "যোগাযোগের ফোন"),
  fieldContactEmail(en: "Contact email (optional)", bn: "যোগাযোগের ইমেইল (ঐচ্ছিক)"),
  fieldManagementType(en: "Management type (optional)", bn: "ব্যবস্থাপনার ধরন (ঐচ্ছিক)"),
  fieldLatitude(en: "Latitude (optional)", bn: "অক্ষাংশ (ঐচ্ছিক)"),
  fieldLongitude(en: "Longitude (optional)", bn: "দ্রাঘিমাংশ (ঐচ্ছিক)"),
  errRequired(en: "Required", bn: "আবশ্যক"),
  errTooLong(en: "Too long", bn: "খুব দীর্ঘ"),
  errNotPositive(en: "Must be greater than 0", bn: "০-এর বেশি হতে হবে"),
  errInvalidPhone(en: "Enter a Bangladesh mobile number (01XXXXXXXXX)", bn: "বাংলাদেশি মোবাইল নম্বর দিন (01XXXXXXXXX)"),
  errInvalidEmail(en: "Enter a valid email address", bn: "সঠিক ইমেইল ঠিকানা দিন"),
  errInvalidCoordinates(en: "Enter both latitude and longitude, or neither", bn: "অক্ষাংশ ও দ্রাঘিমাংশ দুটোই দিন, অথবা কোনোটিই নয়"),
  statusDraft(en: "Draft", bn: "খসড়া"),
  statusSubmitted(en: "Submitted", bn: "জমা দেওয়া হয়েছে"),
  statusUnderReview(en: "Under review", bn: "পর্যালোচনাধীন"),
  statusMoreInformationRequired(en: "More information needed", bn: "আরও তথ্য প্রয়োজন"),
  statusRejected(en: "Rejected", bn: "প্রত্যাখ্যাত"),
  statusApproved(en: "Approved", bn: "অনুমোদিত"),
  statusUnknown(en: "Unknown", bn: "অজানা"),
  typeResidential(en: "Residential", bn: "আবাসিক"),
  typeCommercial(en: "Commercial", bn: "বাণিজ্যিক"),
  typeMixed(en: "Mixed use", bn: "মিশ্র ব্যবহার"),
  relOwner(en: "Owner", bn: "মালিক"),
  relCommitteeMember(en: "Committee member", bn: "কমিটির সদস্য"),
  relPropertyManager(en: "Property manager", bn: "সম্পত্তি ব্যবস্থাপক"),
  relDeveloper(en: "Developer", bn: "ডেভেলপার"),
  relOther(en: "Other", bn: "অন্যান্য"),
  mgmtSelfManaged(en: "Self-managed", bn: "নিজস্ব ব্যবস্থাপনা"),
  mgmtOwnersCommittee(en: "Owners' committee", bn: "মালিক কমিটি"),
  mgmtManagementCompany(en: "Management company", bn: "ব্যবস্থাপনা প্রতিষ্ঠান"),
  mgmtDeveloperManaged(en: "Developer-managed", bn: "ডেভেলপার পরিচালিত"),
  errApplicationIncomplete(en: "Some required fields are missing.", bn: "কিছু প্রয়োজনীয় তথ্য বাকি আছে।"),
  errNotEditable(en: "This application can no longer be changed.", bn: "এই আবেদন আর পরিবর্তন করা যাবে না।"),
  errInvalidTransition(en: "This action is not possible in the current status.", bn: "বর্তমান অবস্থায় এই কাজটি সম্ভব নয়।"),
  errApplicationNotFound(en: "Application not found.", bn: "আবেদনটি পাওয়া যায়নি।"),
  errDocumentNotFound(en: "Document not found.", bn: "নথিটি পাওয়া যায়নি।"),
  errDocumentTooLarge(en: "The file is too large.", bn: "ফাইলটি অনেক বড়।"),
  errUnsupportedDocument(en: "Only PDF, JPG and PNG files are accepted.", bn: "শুধু PDF, JPG ও PNG ফাইল গ্রহণযোগ্য।"),
  errDocumentLimit(en: "This application already has the maximum number of documents.", bn: "এই আবেদনে সর্বোচ্চ সংখ্যক নথি যোগ করা হয়েছে।"),
  errInvalidRequest(en: "Please check the information you entered.", bn: "দেওয়া তথ্য যাচাই করুন।"),
  errUnavailable(en: "The service is temporarily unavailable. Please try again.", bn: "সেবাটি সাময়িকভাবে অনুপলব্ধ। আবার চেষ্টা করুন।"),
  errConnection(en: "Could not connect. Check your internet and try again.", bn: "সংযোগ করা যায়নি। ইন্টারনেট দেখে আবার চেষ্টা করুন।"),
  errUnexpected(en: "Something went wrong. Please try again.", bn: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।"),
  // Add more entries as required
  ;

  final String en;
  final String bn;

  const TextEnum({required this.en, required this.bn});
}

extension TextEnumExtention on TextEnum {
  String get _key => name;
  String get tr => _key.tr;
  String trParams([Map<String, String>? params]) => _key.trParams(params ?? {});
}
