import 'package:get/get.dart';

enum TextEnum {
  appName(en: "App Name", bn: "অ্যাপ নাম"),
  verify(en: "Verify", bn: "যাচাই করুন"),
  send(en: "Send", bn: "পাঠান"),
  submit(en: "Submit", bn: "জমা দিন"),
  ok(en: "OK", bn: "ঠিক আছে"),
  cancel(en: "Cancel", bn: "বাতিল করুন"),
  resend(en: "Resend", bn: "পুনরায় পাঠান"),
  about(en: "About", bn: "সম্পর্কে"),
  contactUs(en: "Contact Us", bn: "যোগাযোগ করুন"),
  loginDescription(
      en: "Enter your credentials to login", bn: "লগইন করতে আপনার তথ্য দিন"),
  loginUpperText(en: "Login to continue", bn: "চালিয়ে যাওয়ার জন্য লগইন করুন"),
  next(en: "Next", bn: "পরবর্তী"),
  otpResend(
      en: "OTP will be sent again in @time", bn: '@time এবার OTP পাঠাবেন'),

  otpVerification(en: "OTP Verification", bn: "OTP যাচাইকরণ"),
  otpSentTo(
      en: "Please check, a verification code has been sent to @phone",
      bn: "@phone নম্বরে একটি যাচাইকরণ কোড পাঠানো হয়েছে"),
  changeNumber(en: "Change Number", bn: "নম্বর পরিবর্তন করুন"),

  phoneNumber(en: "Phone Number", bn: "ফোন নম্বর"),
  pin(en: "PIN", bn: "পিন"),
  createAccount(en: "Create new account", bn: "নতুন অ্যাকাউন্ট তৈরি করুন"),
  // BOS-010 F2 building application
  buildingApplications(en: "My building applications", bn: "আমার ভবন আবেদন"),
  registerBuilding(en: "Register a building", bn: "ভবন নিবন্ধন করুন"),
  newApplication(en: "New application", bn: "নতুন আবেদন"),
  editApplication(en: "Edit application", bn: "আবেদন সম্পাদনা"),
  applicationNumber(en: "Application no. @number", bn: "আবেদন নং @number"),
  noApplications(en: "You have no building applications yet.", bn: "আপনার এখনও কোনো ভবন আবেদন নেই।"),
  saveDraft(en: "Save draft", bn: "খসড়া সংরক্ষণ করুন"),
  submitApplication(en: "Submit application", bn: "আবেদন জমা দিন"),
  confirmSubmit(en: "Submit this application for review? You cannot change it while it is being reviewed.", bn: "পর্যালোচনার জন্য আবেদনটি জমা দেবেন? পর্যালোচনা চলাকালে এটি পরিবর্তন করা যাবে না।"),
  retry(en: "Retry", bn: "আবার চেষ্টা করুন"),
  edit(en: "Edit", bn: "সম্পাদনা"),
  documents(en: "Verification documents", bn: "যাচাইকরণ নথি"),
  noDocuments(en: "No documents yet. Add the deed, a holding tax receipt or other proof.", bn: "এখনও কোনো নথি নেই। দলিল, হোল্ডিং ট্যাক্সের রসিদ বা অন্য প্রমাণ যোগ করুন।"),
  addDocument(en: "Add document", bn: "নথি যোগ করুন"),
  takePhoto(en: "Take photo", bn: "ছবি তুলুন"),
  chooseFromGallery(en: "Choose from gallery", bn: "গ্যালারি থেকে বাছুন"),
  chooseFile(en: "Choose PDF file", bn: "PDF ফাইল বাছুন"),
  removeDocument(en: "Remove", bn: "সরান"),
  confirmRemoveDocument(en: "Remove this document?", bn: "এই নথিটি সরাবেন?"),
  reviewerMessage(en: "Message from the reviewer", bn: "পর্যালোচকের বার্তা"),
  rejectionReason(en: "Reason for rejection", bn: "প্রত্যাখ্যানের কারণ"),
  missingFieldsHint(en: "Complete the required fields to submit.", bn: "জমা দিতে প্রয়োজনীয় তথ্য পূরণ করুন।"),
  draftSaved(en: "Draft saved", bn: "খসড়া সংরক্ষিত হয়েছে"),
  applicationSubmitted(en: "Application submitted", bn: "আবেদন জমা হয়েছে"),
  documentAdded(en: "Document added", bn: "নথি যোগ হয়েছে"),
  sectionBuilding(en: "Building", bn: "ভবন"),
  sectionLocation(en: "Location", bn: "অবস্থান"),
  sectionContact(en: "Contact", bn: "যোগাযোগ"),
  fieldBuildingName(en: "Building name", bn: "ভবনের নাম"),
  fieldBuildingType(en: "Building type", bn: "ভবনের ধরন"),
  fieldAddress(en: "Address (house, road)", bn: "ঠিকানা (বাড়ি, রাস্তা)"),
  fieldArea(en: "Area", bn: "এলাকা"),
  fieldDistrict(en: "District", bn: "জেলা"),
  fieldPostalCode(en: "Postal code (optional)", bn: "পোস্ট কোড (ঐচ্ছিক)"),
  fieldTotalFloors(en: "Total floors (optional)", bn: "মোট তলা (ঐচ্ছিক)"),
  fieldEstimatedUnits(en: "Estimated units (flats, shops)", bn: "আনুমানিক ইউনিট (ফ্ল্যাট, দোকান)"),
  fieldRelationship(en: "Your relationship to the building", bn: "ভবনের সাথে আপনার সম্পর্ক"),
  fieldRelationshipNote(en: "Describe your relationship", bn: "আপনার সম্পর্ক বর্ণনা করুন"),
  fieldContactName(en: "Contact name", bn: "যোগাযোগকারীর নাম"),
  fieldContactPhone(en: "Contact phone", bn: "যোগাযোগের ফোন"),
  fieldContactEmail(en: "Contact email (optional)", bn: "যোগাযোগের ইমেইল (ঐচ্ছিক)"),
  fieldManagementType(en: "Management type (optional)", bn: "ব্যবস্থাপনার ধরন (ঐচ্ছিক)"),
  fieldLatitude(en: "Latitude (optional)", bn: "অক্ষাংশ (ঐচ্ছিক)"),
  fieldLongitude(en: "Longitude (optional)", bn: "দ্রাঘিমাংশ (ঐচ্ছিক)"),
  errRequired(en: "Required", bn: "আবশ্যক"),
  errTooLong(en: "Too long", bn: "খুব দীর্ঘ"),
  errNotPositive(en: "Must be greater than 0", bn: "০-এর বেশি হতে হবে"),
  errInvalidPhone(en: "Enter a Bangladesh mobile number (01XXXXXXXXX)", bn: "বাংলাদেশি মোবাইল নম্বর দিন (01XXXXXXXXX)"),
  errInvalidEmail(en: "Enter a valid email address", bn: "সঠিক ইমেইল ঠিকানা দিন"),
  errInvalidCoordinates(en: "Enter both latitude and longitude, or neither", bn: "অক্ষাংশ ও দ্রাঘিমাংশ দুটোই দিন, অথবা কোনোটিই নয়"),
  statusDraft(en: "Draft", bn: "খসড়া"),
  statusSubmitted(en: "Submitted", bn: "জমা দেওয়া হয়েছে"),
  statusUnderReview(en: "Under review", bn: "পর্যালোচনাধীন"),
  statusMoreInformationRequired(en: "More information needed", bn: "আরও তথ্য প্রয়োজন"),
  statusRejected(en: "Rejected", bn: "প্রত্যাখ্যাত"),
  statusApproved(en: "Approved", bn: "অনুমোদিত"),
  statusUnknown(en: "Unknown", bn: "অজানা"),
  typeResidential(en: "Residential", bn: "আবাসিক"),
  typeCommercial(en: "Commercial", bn: "বাণিজ্যিক"),
  typeMixed(en: "Mixed use", bn: "মিশ্র ব্যবহার"),
  relOwner(en: "Owner", bn: "মালিক"),
  relCommitteeMember(en: "Committee member", bn: "কমিটির সদস্য"),
  relPropertyManager(en: "Property manager", bn: "সম্পত্তি ব্যবস্থাপক"),
  relDeveloper(en: "Developer", bn: "ডেভেলপার"),
  relOther(en: "Other", bn: "অন্যান্য"),
  mgmtSelfManaged(en: "Self-managed", bn: "নিজস্ব ব্যবস্থাপনা"),
  mgmtOwnersCommittee(en: "Owners' committee", bn: "মালিক কমিটি"),
  mgmtManagementCompany(en: "Management company", bn: "ব্যবস্থাপনা প্রতিষ্ঠান"),
  mgmtDeveloperManaged(en: "Developer-managed", bn: "ডেভেলপার পরিচালিত"),
  errApplicationIncomplete(en: "Some required fields are missing.", bn: "কিছু প্রয়োজনীয় তথ্য বাকি আছে।"),
  errNotEditable(en: "This application can no longer be changed.", bn: "এই আবেদন আর পরিবর্তন করা যাবে না।"),
  errInvalidTransition(en: "This action is not possible in the current status.", bn: "বর্তমান অবস্থায় এই কাজটি সম্ভব নয়।"),
  errApplicationNotFound(en: "Application not found.", bn: "আবেদনটি পাওয়া যায়নি।"),
  errDocumentNotFound(en: "Document not found.", bn: "নথিটি পাওয়া যায়নি।"),
  errDocumentTooLarge(en: "The file is too large.", bn: "ফাইলটি অনেক বড়।"),
  errUnsupportedDocument(en: "Only PDF, JPG and PNG files are accepted.", bn: "শুধু PDF, JPG ও PNG ফাইল গ্রহণযোগ্য।"),
  errDocumentLimit(en: "This application already has the maximum number of documents.", bn: "এই আবেদনে সর্বোচ্চ সংখ্যক নথি যোগ করা হয়েছে।"),
  errInvalidRequest(en: "Please check the information you entered.", bn: "দেওয়া তথ্য যাচাই করুন।"),
  errUnavailable(en: "The service is temporarily unavailable. Please try again.", bn: "সেবাটি সাময়িকভাবে অনুপলব্ধ। আবার চেষ্টা করুন।"),
  errConnection(en: "Could not connect. Check your internet and try again.", bn: "সংযোগ করা যায়নি। ইন্টারনেট দেখে আবার চেষ্টা করুন।"),
  errUnexpected(en: "Something went wrong. Please try again.", bn: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।"),
  uoBuildings(en: "My Buildings", bn: "আমার ভবন"),
  uoProperties(en: "My Properties", bn: "আমার সম্পত্তি"),
  uoInvitations(en: "Invitations", bn: "আমন্ত্রণ"),
  uoUnits(en: "Units", bn: "ইউনিট"),
  uoFloors(en: "Floors", bn: "তলা"),
  uoMembers(en: "Members", bn: "সদস্য"),
  uoEmpty(en: "No records to show.", bn: "কোনো তথ্য নেই।"),
  uoDenied(en: "Access is unavailable or has been revoked. Return to My Buildings.", bn: "প্রবেশাধিকার নেই বা বাতিল হয়েছে। আমার ভবনে ফিরে যান।"),
  uoReadOnly(en: "This building is read-only.", bn: "এই ভবনের তথ্য শুধু দেখা যাবে।"),
  uoRetry(en: "Retry", bn: "আবার চেষ্টা"),
  uoRefresh(en: "Refresh", bn: "রিফ্রেশ"),
  uoClaim(en: "Accept invitation", bn: "আমন্ত্রণ গ্রহণ"),
  uoClaimInfo(en: "Accepting links your account to this building. Ownership is assigned separately.", bn: "গ্রহণ করলে আপনার অ্যাকাউন্ট এই ভবনের সাথে যুক্ত হবে। মালিকানা আলাদাভাবে বরাদ্দ হবে।"),
  uoInvite(en: "Invite owner", bn: "মালিককে আমন্ত্রণ"),
  uoPhone(en: "Phone number", bn: "ফোন নম্বর"),
  uoReason(en: "Reason", bn: "কারণ"),
  uoRevoke(en: "Revoke access", bn: "প্রবেশাধিকার বাতিল"),
  uoRevokeInfo(en: "Revoke this invitation or membership? Existing legal ownership and history are preserved.", bn: "এই আমন্ত্রণ বা সদস্যপদ বাতিল করবেন? বিদ্যমান আইনগত মালিকানা ও ইতিহাস সংরক্ষিত থাকবে।"),
  uoCreateUnit(en: "Add unit", bn: "ইউনিট যোগ"),
  uoEditUnit(en: "Edit unit", bn: "ইউনিট সম্পাদনা"),
  uoCreateFloor(en: "Add floor", bn: "তলা যোগ"),
  uoEditFloor(en: "Edit floor", bn: "তলা সম্পাদনা"),
  uoNumber(en: "Unit number", bn: "ইউনিট নম্বর"),
  uoFloor(en: "Floor", bn: "তলা"),
  uoLabel(en: "Floor label", bn: "তলার নাম"),
  uoKind(en: "Floor kind", bn: "তলার ধরন"),
  uoOrder(en: "Display order", bn: "প্রদর্শনের ক্রম"),
  uoType(en: "Unit type", bn: "ইউনিটের ধরন"),
  uoArea(en: "Area (sq ft)", bn: "আয়তন (বর্গফুট)"),
  uoBedrooms(en: "Bedrooms (optional)", bn: "শয়নকক্ষ (ঐচ্ছিক)"),
  uoRate(en: "Maintenance rate (optional)", bn: "রক্ষণাবেক্ষণের হার (ঐচ্ছিক)"),
  uoNotes(en: "Notes (optional)", bn: "নোট (ঐচ্ছিক)"),
  uoSave(en: "Save", bn: "সংরক্ষণ"),
  uoConfirm(en: "Confirm", bn: "নিশ্চিত করুন"),
  uoBatch(en: "Add multiple units", bn: "একাধিক ইউনিট যোগ"),
  uoPreview(en: "Preview", bn: "প্রাকদর্শন"),
  uoImport(en: "Import CSV / Excel", bn: "CSV / Excel আমদানি"),
  uoPattern(en: "Number pattern, e.g. {floor}{letter}", bn: "নম্বরের ধরন, যেমন {floor}{letter}"),
  uoCount(en: "Units per floor (1–500)", bn: "প্রতি তলায় ইউনিট (১–৫০০)"),
  uoStart(en: "Starting number", bn: "শুরুর নম্বর"),
  uoTemplate(en: "Copy layout from floor (optional)", bn: "তলা থেকে বিন্যাস কপি (ঐচ্ছিক)"),
  uoBatchInfo(en: "Review every row. All rows are saved together or none are saved.", bn: "প্রতিটি সারি যাচাই করুন। সব সারি একসাথে সংরক্ষিত হবে, অথবা একটিও হবে না।"),
  uoCommit(en: "Confirm and save all units", bn: "নিশ্চিত করে সব ইউনিট সংরক্ষণ"),
  uoRecheck(en: "Validate edited rows", bn: "সম্পাদিত সারি যাচাই"),
  uoInvalidRows(en: "Correct the row errors before saving.", bn: "সংরক্ষণের আগে সারির ত্রুটি সংশোধন করুন।"),
  uoSaved(en: "Saved successfully.", bn: "সফলভাবে সংরক্ষিত।"),
  uoOwnedCount(en: "Owned units", bn: "মালিকানাধীন ইউনিট"),
  uoExpires(en: "Expires", bn: "মেয়াদ শেষ"),
  uoShare(en: "Ownership share (%)", bn: "মালিকানার অংশ (%)"),
  uoConflict(en: "These records changed or conflict with existing data. Refresh and review before retrying.", bn: "তথ্য পরিবর্তিত হয়েছে বা বিদ্যমান তথ্যের সাথে মিলছে না। রিফ্রেশ করে যাচাই করুন।"),
  uoInviteExpired(en: "This invitation expired or was revoked. Ask the building administrator for a new invitation.", bn: "আমন্ত্রণের মেয়াদ শেষ বা বাতিল হয়েছে। ভবন প্রশাসকের কাছে নতুন আমন্ত্রণ চান।"),
  uoFileUnsupported(en: "Choose a CSV or XLSX file without formulas or macros.", bn: "সূত্র বা ম্যাক্রো ছাড়া CSV বা XLSX ফাইল বাছুন।"),
  uoFileTooLarge(en: "The selected file is too large.", bn: "বাছাই করা ফাইলটি অনেক বড়।"),
  uoNeedFloor(en: "Add a floor before adding units.", bn: "ইউনিট যোগ করার আগে একটি তলা যোগ করুন।"),
  uoChooseFloor(en: "Select at least one destination floor.", bn: "অন্তত একটি গন্তব্য তলা বাছুন।"),
  uoFlat(en: "Flat", bn: "ফ্ল্যাট"),
  uoParking(en: "Parking", bn: "পার্কিং"),
  uoStorage(en: "Storage", bn: "স্টোর"),
  uoCommercial(en: "Commercial", bn: "বাণিজ্যিক"),
  uoCommon(en: "Common", bn: "সাধারণ"),
  uoOther(en: "Other", bn: "অন্যান্য"),
  uoBasement(en: "Basement", bn: "বেজমেন্ট"),
  uoGround(en: "Ground", bn: "নিচতলা"),
  uoRegular(en: "Regular", bn: "সাধারণ তলা"),
  uoRoof(en: "Roof", bn: "ছাদ"),
  uoOnboarding(en: "Onboarding", bn: "প্রস্তুতি চলছে"),
  uoActive(en: "Active", bn: "সক্রিয়"),
  uoSuspended(en: "Suspended", bn: "স্থগিত"),
  uoOwner(en: "Owner", bn: "মালিক"),
  uoAdmin(en: "Building admin", bn: "ভবন প্রশাসক"),
  uoPending(en: "Pending", bn: "অপেক্ষমাণ"),
  uoClaimed(en: "Accepted", bn: "গৃহীত"),
  uoRevoked(en: "Revoked", bn: "বাতিল"),
  uoExpired(en: "Expired", bn: "মেয়াদোত্তীর্ণ"),
  uoOwnership(en: "Ownership", bn: "মালিকানা"),
  uoHistory(en: "Ownership history", bn: "মালিকানার ইতিহাস"),
  uoNone(en: "None", bn: "কোনোটিই নয়"),
  uoEdit(en: "Edit", bn: "সম্পাদনা"),
  // Add more entries as required
  ;

  final String en;
  final String bn;

  const TextEnum({required this.en, required this.bn});
}

extension TextEnumExtention on TextEnum {
  String get _key => name;
  String get tr => _key.tr;
  String trParams([Map<String, String>? params]) => _key.trParams(params ?? {});
}
